import React from 'react'
import Layout from './components/Layout'
import TerminalView from './components/TerminalView'
import { motion } from 'framer-motion'
import { Sparkles, Box, Code, Layers } from 'lucide-react'

function App() {
  return (
    <Layout>
      <div className="h-full grid grid-rows-[1fr_auto] gap-6">
        {/* Top Feature Cards / Workspace Content */}
        <div className="grid grid-cols-2 gap-6 overflow-hidden">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="glass-panel p-6 flex flex-col justify-center items-center text-center group cursor-pointer hover:border-primary-light/40 transition-all border-dashed"
          >
            <div className="w-16 h-16 rounded-full bg-primary-light/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
              <Sparkles className="text-primary-light" size={32} />
            </div>
            <h3 className="font-bold text-lg mb-2">A2UI Preview</h3>
            <p className="text-sm text-white/40 max-w-xs">
              Interactive components generated by Agent will appear here in real-time.
            </p>
          </motion.div>

          <div className="grid grid-rows-2 gap-4">
            <QuickToolCard icon={<Box />} title="File Explorer" desc="Manage local workspace files" />
            <QuickToolCard icon={<Code />} title="Code Editor" desc="Review and edit generated scripts" />
          </div>
        </div>

        {/* Bottom Terminal Section */}
        <div className="h-64">
          <TerminalView />
        </div>
      </div>
    </Layout>
  )
}

const QuickToolCard = ({ icon, title, desc }: { icon: React.ReactNode, title: string, desc: string }) => (
  <motion.div
    whileHover={{ x: 4 }}
    className="glass-panel p-4 flex items-center gap-4 cursor-pointer hover:bg-white/5 transition-colors"
  >
    <div className="p-2 bg-white/5 rounded-lg text-primary-light">
      {icon}
    </div>
    <div>
      <h4 className="font-medium text-sm">{title}</h4>
      <p className="text-[11px] text-white/30">{desc}</p>
    </div>
    <Layers size={14} className="ml-auto text-white/10" />
  </motion.div>
)

export default App
